version: "3"
services:
  activemq:
    build:
      ./activemq-docker
    ports:
      - 61616:61616
      - 8161:8161
  shop:
    build:
      ./shop
    ports:
      - 8888:8080
    depends_on:
      - activemq
  discount:
    build:
      ./discount
    ports:
      - 8889:8080
    depends_on:
      - activemq