INSERT INTO CARTS (ORDER_ID, FLOWER_ID, NUMBER, SUM_PRICE) VALUES(2,1,5,null);
INSERT INTO CARTS (ORDER_ID, FLOWER_ID, NUMBER, SUM_PRICE) VALUES(2,2,6,null);
INSERT INTO CARTS (ORDER_ID, FLOWER_ID, NUMBER, SUM_PRICE) VALUES(3,3,2,null);
INSERT INTO CARTS (ORDER_ID, FLOWER_ID, NUMBER, SUM_PRICE) VALUES(3,4,2,null);