INSERT INTO CARTS (ORDER_ID, FLOWER_ID, NUMBER, SUM_PRICE_WITHOUT_DISCOUNT, SUM_PRICE_WITH_DISCOUNT) VALUES(2,1,5,null,null);
INSERT INTO CARTS (ORDER_ID, FLOWER_ID, NUMBER, SUM_PRICE_WITHOUT_DISCOUNT, SUM_PRICE_WITH_DISCOUNT) VALUES(2,2,6,null,null);
INSERT INTO CARTS (ORDER_ID, FLOWER_ID, NUMBER, SUM_PRICE_WITHOUT_DISCOUNT, SUM_PRICE_WITH_DISCOUNT) VALUES(3,3,2,null,null);
INSERT INTO CARTS (ORDER_ID, FLOWER_ID, NUMBER, SUM_PRICE_WITHOUT_DISCOUNT, SUM_PRICE_WITH_DISCOUNT) VALUES(3,4,2,null,null);