CREATE TABLE USERS (
ID BIGINT PRIMARY KEY auto_increment,
login VARCHAR(255) UNIQUE,
password VARCHAR(255) NOT NULL,
NAME VARCHAR(255),
address VARCHAR(255),
phoneNumber VARCHAR(255),
score DECIMAL(20,2),
sale INT,
role VARCHAR(8) CHECK (role IN ('ADMIN', 'CUSTOMER'))
);


CREATE TABLE ORDERS (
ID BIGINT PRIMARY KEY auto_increment,
sumPrice DECIMAL(20,2),
dateCreate DATE,
dateClose DATE,
status VARCHAR(6) CHECK (status IN ('OPENED', 'PAID', 'CLOSED')),
userId BIGINT,
FOREIGN KEY(userId) REFERENCES users(id)
);

CREATE TABLE FLOWERS (
ID BIGINT PRIMARY KEY auto_increment,
name VARCHAR(255),
price DECIMAL(20,2),
number INT
);