CREATE SEQUENCE USERS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE TABLE USERS (
ID BIGINT DEFAULT USERS_SEQ.NEXTVAL PRIMARY KEY,
LOGIN VARCHAR(255) UNIQUE,
PASSWORD VARCHAR(255) NOT NULL,
NAME VARCHAR(255),
ADDRESS VARCHAR(255),
PHONE_NUMBER VARCHAR(255),
CASH DECIMAL(20,2),
DISCOUNT INT,
ROLE VARCHAR(8) CHECK (ROLE IN ('ADMIN', 'CUSTOMER'))
);

CREATE SEQUENCE ORDERS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE TABLE ORDERS (
ID BIGINT DEFAULT ORDERS_SEQ.NEXTVAL PRIMARY KEY,
SUM_PRICE DECIMAL(20,2),
DATE_CREATE TIMESTAMP,
DATE_CLOSE TIMESTAMP,
STATUS VARCHAR(6) CHECK (STATUS IN ('OPENED', 'PAID', 'CLOSED')),
USER_ID BIGINT,
FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
);

CREATE SEQUENCE FLOWERS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE TABLE FLOWERS (
ID BIGINT DEFAULT FLOWERS_SEQ.NEXTVAL PRIMARY KEY,
NAME VARCHAR(255),
PRICE DECIMAL(20,2),
NUMBER INT
);

CREATE SEQUENCE CARTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE TABLE CARTS (
ID BIGINT DEFAULT CARTS_SEQ.NEXTVAL PRIMARY KEY,
ORDER_ID BIGINT,
FLOWER_ID BIGINT,
NUMBER INT,
SUM_PRICE DECIMAL(20,2),
FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ID),
FOREIGN KEY(FLOWER_ID) REFERENCES FLOWERS(ID)
);