CREATE TABLE USERS (
ID BIGINT PRIMARY KEY auto_increment,
login VARCHAR(255) UNIQUE,
password VARCHAR(255) NOT NULL,
NAME VARCHAR(255),
address VARCHAR(255),
phone_Number VARCHAR(255),
score DECIMAL(20,2),
sale INT,
role VARCHAR(8) CHECK (role IN ('ADMIN', 'CUSTOMER'))
);


CREATE TABLE ORDERS (
ID BIGINT PRIMARY KEY auto_increment,
sum_Price DECIMAL(20,2),
date_Create TIMESTAMP,
date_Close TIMESTAMP,
status VARCHAR(6) CHECK (status IN ('OPENED', 'PAID', 'CLOSED')),
user_Id BIGINT,
FOREIGN KEY(user_Id) REFERENCES users(id)
);

CREATE TABLE FLOWERS (
ID BIGINT PRIMARY KEY auto_increment,
name VARCHAR(255),
price DECIMAL(20,2),
number INT
);