INSERT INTO ORDERS (SUM_PRICE, DATE_CREATE, DATE_CLOSE, STATUS, USER_ID) VALUES(null,null,null,'OPENED',1);
INSERT INTO ORDERS (SUM_PRICE, DATE_CREATE, DATE_CLOSE, STATUS, USER_ID) VALUES(null,null,null,'PAID',1);
INSERT INTO ORDERS (SUM_PRICE, DATE_CREATE, DATE_CLOSE, STATUS, USER_ID) VALUES(null,null,null,'CLOSED',1);
