CREATE SEQUENCE CARTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE TABLE CARTS (
ID BIGINT DEFAULT CARTS_SEQ.NEXTVAL PRIMARY KEY,
ORDER_ID BIGINT,
FLOWER_ID BIGINT,
NUMBER INT,
FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ID),
FOREIGN KEY(FLOWER_ID) REFERENCES FLOWERS(ID)
);