INSERT INTO ORDERS (SUM_PRICE_WITHOUT_DISCOUNT, SUM_PRICE_WITH_DISCOUNT, DATE_CREATE, DATE_CLOSE, STATUS, USER_ID) VALUES(null,null,null,null,'OPENED',1);
INSERT INTO ORDERS (SUM_PRICE_WITHOUT_DISCOUNT, SUM_PRICE_WITH_DISCOUNT, DATE_CREATE, DATE_CLOSE, STATUS, USER_ID) VALUES(null,null,null,null,'PAID',1);
INSERT INTO ORDERS (SUM_PRICE_WITHOUT_DISCOUNT, SUM_PRICE_WITH_DISCOUNT, DATE_CREATE, DATE_CLOSE, STATUS, USER_ID) VALUES(null,null,null,null,'CLOSED',1);
